[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"
  HUGO_VERSION = "0.84.4"

[context.production]
  command = "npx hugo --gc --minify "
[context.deploy-preview]
  command = "npx hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npx hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next]
  command = "npx hugo --gc --minify"

[context.next.environment]
  HUGO_ENV = "next"

[dev]
  framework = "#custom"
  command = "npx rimraf public resources functions && npx hugo server --bind=0.0.0.0 --disableFastRender"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false
